### ISSUE TITLE
Bower includes wrong path in index.html

### ISSUE THREAD

**Issue by airasheed** [dpiccone/ng-pageslide#102]
When installing via bower. Bower places the file in the index.html with the following path:

<script src="bower_components/angular-pageslide-directive/build/angular-pageslide-directive.min.js"></script>

it should read:

<script src="bower_components/angular-pageslide-directive/dist/angular-pageslide-directive.min.js"></script>

The word "build" should be "dist".

It seems that the bower.cc is incorrect.

**Comment by dpiccone** [comment]
https://github.com/dpiccone/ng-pageslide/blob/master/bower.json
The main file in bower.json seems to point to the correct one, closing this.
