### ISSUE TITLE
As a user, version 1.1.1 breaks animations and disallows showing of content onLoad

### ISSUE THREAD

**Issue by iamaaron** [dpiccone/ng-pageslide#103]
This line:

https://github.com/dpiccone/ng-pageslide/blob/master/src/angular-pageslide-directive.js#L130

Breaks animations and disallows showing of content onLoad.

Why did you remove psCloak as an option if it was introduced as a feature of 1.0?

Alternatively, is there anyway to achieve the same functionality without psCloak? (doesn't appear so).

**Comment by dpiccone** [comment]
You can use the last of version 1.0 which has still support for that.

The interface of this directive has grown too much out of the original project scope, and why it's interesting to understand and cover all the use cases, it made it difficult to maintain.
