### ISSUE TITLE
can not set ps-click-outside option to false

### ISSUE THREAD

**Issue by StasTelnov** [dpiccone/ng-pageslide#107]
Because of 'psClickOutside' param is set through '@', it is interpreted as string, not as boolean. Because of that, I can't 'psClickOutside' param set to false:
 
param.clickOutside = $scope.psClickOutside === false ? false : true;

It is should be something like this:

param.clickOutside = $scope.psClickOutside === 'false' ? false : true;

**Comment by dpiccone** [comment]
True, sadly I had no time to test it the other way around, would that bother you a PR?

**Comment by StasTelnov** [comment]
Do you want me to do pull request?

**Comment by dpiccone** [comment]
Yes, that would be quickier

**Comment by StasTelnov** [comment]
Ok :)
