### ISSUE TITLE
ie11 slider flashes 

### ISSUE THREAD

**Issue by sajit** [dpiccone/ng-pageslide#109]
When I load the page slide in ie11, on page load the slider content intialy flashes & quickly slides out.

Expected behavior is that its not visible on page load but comes into focus on click of a button.

works fine on firefox and chrome. Any advice?

**Comment by dpiccone** [comment]
I would say the error could be in the scope variable passed to ps-open.

Since the examples are working fine in ie11, I'll close this issue.

**Comment by mig-foxbat** [comment]
I am too getting the same issue in chrome as well but not in firefox. This issue happens to me only when the route is changed but not in page reload. for eg if route r1 has ng-pageslide and if move from r2 to r1 I see my pageslide content slide back. This issue doesn't occur if I refresh page/route r1.

**Comment by jwhitmarsh** [comment]
@dpiccone can you supply more detail on this please? What would be wrong with the variable to cause this?
