### ISSUE TITLE
Fixed push issue

### ISSUE THREAD

**Issue by marie-dk** [dpiccone/ng-pageslide#111]
The push option didn't work for me. I noticed that only "left" and "right" css was set on the body element. The push option obviously also needs transition and absolute position. I got it working by changing line 98 from...

`if (param.squeeze) {`

... to ...

`if (param.squeeze || param.push) {`

Its weird since your demo works like a charm...

My environment is:
Angular 1.5.5
Bootstrap 3.3.6
Angular-ui-bootstrap 1.3.2

**Comment by dpiccone** [comment]
https://github.com/dpiccone/ng-pageslide/commit/9f1a1cb111d70c15be269db3ad72eb3ee7e6abfe#diff-ed0675d1c16fbd9f3e9ba4afdc335f08R97
