### ISSUE TITLE
ps-size breaks ps-push?

### ISSUE THREAD

**Issue by bobwiller** [dpiccone/ng-pageslide#112]
If I have a pageslide that looks like this:
    `<div pageslide ps-open="vm.checked" ps-side="left" ps-push="true">`
Everything works as expected.

As soon as i add a ps-size attribute, it will ignore the ps-push="true".
Is this a known issue, bug, or by design?
Thanks,
Bob

**Comment by dpiccone** [comment]
Nope, I would expect push and size playing together.
Are you changing the size dynamically?

**Comment by dpiccone** [comment]
I played around in the examples and this seems to work
```
            <h3>Push content</h3>
            <div ng-controller="pageslideCtrl">
                <a class="tiny button" href="" ng-click="toggle()">Open Sidebar</a>
                <div pageslide ps-open="checked" ps-side="left" ps-push="true" ps-size='{{size}}'>
                    <div style="padding:20px" id="demo-right">
                        <h2>Hello Pageslide</h2>
                        <p>Put here whatever you want</p>
                        <p>psSize <input type="text" ng-model="size" ></p>
                        <a ng-click="toggle()" class="button" >Close</a>
                    </div>
                </div>
            </div>
```

**Comment by bobwiller** [comment]
Thanks -> got it working now -> It doesn't work - turns out you need the 'px' as part of the size.  I was using ps-size='400'.  

Appreciate your help!
BW
