### ISSUE TITLE
ps-container working but slide is messed up

### ISSUE THREAD

**Issue by nomanr** [dpiccone/ng-pageslide#114]
```
<div id = "container_body">
//.....
</div>

<pageslide ps-open="pagerOpened" ps-side="left" ps-push="true" ps-size="85%" ps-click-outside="true" ps-body-class="true" ps-custom-top="50px" ps-container="container_body">
//.....
</pageslide>
```

Screenshot 
<a href="http://tinypic.com?ref=4kxyxk" target="_blank"><img src="http://i66.tinypic.com/4kxyxk.png" border="0" alt="Image and video hosting by TinyPic"></a>

Slider moves right when I open it with the container. 
Can anyone please tell me what I am doing wrong?? 
Thanks

**Comment by tusharbhatta** [comment]
Can you put a jsfiddle with your problem ? Hard to say anything by just seeing a screenshot.

**Comment by dpiccone** [comment]
I notice you are using ps-container along with ps-push, what is the behaviour do you expect?
Is the directive still working in full screen?

**Comment by dpiccone** [comment]
closing as the two cannot be combined anymore https://github.com/dpiccone/ng-pageslide/blob/master/src/angular-pageslide-directive.js#L52
