### ISSUE TITLE
using ps-squeeze with ps-container, both the container & the pageslide right 300px

### ISSUE THREAD

**Issue by Ragnarokmagic** [dpiccone/ng-pageslide#115]
firstly, Thanks for great pageslide!

some strange behaviors happened when I use ps - squeeze with ps-container.

I wish the pageslide appear from right of the container and squeeze the contents in the container
But seems now pageslide will first squeeze the container and then appear from the right
so there is a blank between the container and the browser.

here my code
```
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 id="container" style="height: 500px">
         
        </div>
        <div ng-controller="myCtrl">
             <button ng-click="toggler()">test</button>
             <pageslide ps-open="checked" ps-click-outside="false" ps-squeeze="true"
                               ps-container="container">
                       <div></div>
             </pageslide>
        </div>
    </div> 
</div>
```

![20160622155637](https://cloud.githubusercontent.com/assets/20083857/16258905/920efeda-3892-11e6-8abd-79c3a8c279a3.png)
![20160622155654](https://cloud.githubusercontent.com/assets/20083857/16258906/9212cfec-3892-11e6-96f0-bef207cd7412.png)

I think ps-squeeze should influence the inner level of the container not itself. 
Are my code wrong? please give me some suggestions.

Best regards!

**Comment by Ragnarokmagic** [comment]
By the way，just set right attr of the div won't squeeze but same as push
Now I change the source code
set `slider.style.right = attrs.psCustomRight || '-' + param.size;`
in close function` 'if(squeeze) body.style.width = '100%';'`
in open function ` if(squeeze) body.style.width = "calc("+body.style.width+"-"+param.size+")";`
in body setup body.style.transitionProperty add width

**Comment by dpiccone** [comment]
Hi, thanks for reporting this.
> I think ps-squeeze should influence the inner level of the container not itself. 
You're right. And the same would be if using ps-push.

However I am considering rewriting the directive to avoid manipulating the container size, this would drop the support for psSqueeze, that,  in my opinion, has a very little use compared to the push function.

Marking this as a bug for now :100:

**Comment by dpiccone** [comment]
I started working on a refactoring the directive, and dropping unmaintained features.

ps-squeeze won't be supported on v2
