### ISSUE TITLE
Added ps-click-inside option

### ISSUE THREAD

**Issue by marie-dk** [dpiccone/ng-pageslide#116]
Just a suggestion...
I need the slider to close even if state does not change (e.g. user clicks the menu item of the current state). Actually, any click inside the menu slider, must close it. So I added the ps-click-inside option. It is identical to the ps-click-outside option... only difference is, it checks if the click is inside the menu, instead of outside.

I am a github noob. I have no idea how to contribute. But since it is really easy to add, I'll leave it up to you to decide if this should be included in a future version :-)

**Comment by dpiccone** [comment]
Hi @marie-dk I understand the requirement but it's not something that should be added to the directive.
While click-outside it's a pattern found in almost any modal interaction, this one I see it very specific to your case.
You could just add a listener on the pageslide content yourself if this is needed.
Thanks for the suggestion anyway :v:
