### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by andrew-jones** [dpiccone/ng-pageslide#12]
JQuery mobile has 3 different expose options.  Overlay, reveal and push.  Would be cool to see those options here.

http://demos.jquerymobile.com/1.4.2/panel/

**Comment by yabasha** [comment]
Any updates?

**Comment by dpiccone** [comment]
Yes, you can pull from bower v1.0.1 it has push and squeeze, however they make assumption on your layout. 

It is similar to the one above, but for the *reveal* effect I have to rework the main logic.
