### ISSUE TITLE
ps-custom-height

### ISSUE THREAD

**Issue by amirsabersharifi** [dpiccone/ng-pageslide#124]
In the old version there was an attribute named, psCustomHeight. It was pretty handy in terms of being able to set the size of the menu, but it seems, it's removed from the current version, is there any way to bring that back?

**Comment by dpiccone** [comment]
It was undocumented and unmaintained. Last version to support it is v1.4.4 that's the one to use if you need it.

**Comment by amirsabersharifi** [comment]
I believe this is something much need, would it be a good idea to add it
back and document it?

**Comment by dpiccone** [comment]
I understand that there's an use case, but it can easily be served by adding a custom height container inside the panel, the scope of the directive is just slide the panel in and out.
