### ISSUE TITLE
ps-push without pushing off screen (push but resize)

### ISSUE THREAD

**Issue by umdstu** [dpiccone/ng-pageslide#139]
i'd like toggling of the slide to push into the container (like ps-push=true does), but instead of pushing off screen 300px, have it become 300px less wide, if that makes sense;

i'm able to accomplish this by commenting out the line in psOpen() for body.style.right = '-' + param.size;

Is there a built in, more robust way, in which to accomplish this?

**Comment by dpiccone** [comment]
https://github.com/dpiccone/ng-pageslide/pull/138

**Comment by dapriett** [comment]
I was looking for the same thing - got it to work by doing this in my css:

```
body {
  left: 0 !important;
}
```
