### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by gman7911** [dpiccone/ng-pageslide#144]
Is it possible to have the content within the slider scroll vertically?

**Comment by songokudbz** [comment]
I have a fix for that.

Just add the following: **ng-class="{'scroll-fix-slider': true}"** in the pageslider div and add the following CSS: 
.scroll-fix-slider{
        overflow-y: scroll;
        overflow-x: hidden;
}

Hope it helps. Anyhow he should integrate this I agree.

**Comment by dpiccone** [comment]
I prefer not making assumption on which content people will insert into the pageslide, if they want to put a large block of text in that they should update the their css accordingly using the classes the pageslide provides.

**Comment by songokudbz** [comment]
I thought that it will be easy to integrate this, but of course, this is your creation and I will respect your wish. @gman7911 please add separate CSS then.

**Comment by vofili** [comment]
Thanks @songokudbz so much i really needed a scroller on pageslider
