### ISSUE TITLE
dynamic div id

### ISSUE THREAD

**Issue by yppeaxy** [dpiccone/ng-pageslide#18]
Hi there,
nice directive!
Have you tried making this work with dynamic target div ids?

I mean something like this:

````
<a pageslide="left" ps-speed="0.5" ps-class="some-pageslide" ps-custom-top="5%" 
     ps-custom-left="0%" ps-parent="foo" href="#{{someId}}" >My slide out</a>
````

thanks!

**Comment by dpiccone** [comment]
I changed the way the pageslide is taking the content because it was conflicting with routing, now the directive can be applied ony to div blocks. Not sure if this is pertinent anymore, would be good to see an use case for this.
