### ISSUE TITLE
ps-custom-left dynamically

### ISSUE THREAD

**Issue by latxor** [dpiccone/ng-pageslide#29]
Hello, can you help with this issue?

I really want to change the percentage of ps-custom-left dynamically, something like: 

< pageslide  ps-open="hideSearchModule" ps-side="bottom" ps-speed="0.5" ps-size="330px" ps-custom-left="myPercentage"  >

How can i do that?

Thanks.

PD: Sorry for my english, greetings from colombia :)

**Comment by dpiccone** [comment]
Hi, you can change use a function and evaluate it then pass the value to ps-custom-left, something like {{getCustomLeft()}} but, with the current code, the value will be calculated only when the directive is created. Greetings also to you my friend :+1:
