### ISSUE TITLE
does this support url navigation with ui-router?

### ISSUE THREAD

**Issue by ajbraus** [dpiccone/ng-pageslide#30]
does this support url navigation with ui-router?

**Comment by idoo** [comment]
@ajbraus what you mean? with hash links?
you can use variable 'checked' for show sidebar

```html
<pageslide ps-open="checked">

**Comment by dpiccone** [comment]
In version 1.0 this is the only way to open the pageslide. Using href and ps-target conflicts with routing libraries, you can use ngRoute and resolve the state to the controller which will open the pageslide
