### ISSUE TITLE
I am using this directive for hide and show my pane, but getting error

### ISSUE THREAD

**Issue by ankurshah32** [dpiccone/ng-pageslide#31]
I am using this directive for hide and show my pane, but getting this error

 Error: You have to elements inside the <pageslide> or you have not specified a target href.

Please have look at my code 
![issue](https://cloud.githubusercontent.com/assets/4920253/5870511/f5069c3a-a2f4-11e4-9513-d3eae8da07c3.png)

Can you please let me know how do i integrate with this.

**Comment by dpiccone** [comment]
With version 1.0.0 pt-target has been removed, you just need to wrap the content inside <pageslide><div>...</div></pageslide>
