### ISSUE TITLE
opening panel when mouse is at certain point

### ISSUE THREAD

**Issue by jstevenson81** [dpiccone/ng-pageslide#32]
Here's my code:

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
    <link href="Content/bootstrap.css" rel="stylesheet" />

    <script src="scripts/angular.js"></script>
    <script src="scripts/angular-pageSlide-directive.js"></script>
    <script src="scripts/jquery-2.1.3.js"></script>

    <style>
        .ng-pageslide {
            background: #eee;
        }
    </style>

</head>
<body ng-app="app" ng-controller="testing as vm">
    <div class="container">

        <div class="row">
            <div class="col-md-12">
                <button class="btn btn-lg" pageslide ps-side="top" ps-speed="0.5" href="#demo-top">Open Demo</button>
                <button class="btn btn-lg" pageslide ps-side="bottom" ps-speed="0.5" href="#demo-bottom">Open Demo</button>
                <pageslide ps-side="bottom" ps-open="vm.showme" ps-size="100px">
                    <div>
                        Blah
                    </div>
                </pageslide>
            </div>
        </div>

    </div>
    <div style="padding: 20px;" id="demo-bottom">
        <h2>Hello Pageslide</h2>
        <p>Put here whatever you want</p>
        <a id="demo-bottom-close" i class="button">Close</a>
    </div>
    <div style="padding: 20px;" id="demo-top">
        <h2>Hello Pageslide</h2>
        <p>Put here whatever you want</p>
        <a id="demo-top-close" i class="button">Close</a>
    </div>

    <script type="text/javascript">

        (function () {

            angular.module('app', ['pageslide-directive'])
                .controller('testing', testing);
            function testing() {
                var vm = this;

                vm.showme = false;

                $(window).mousemove(function (e) {
                    if (e.pageX <= 10) {
                        vm.showme = true;
                    } else {
                        vm.showme = false;
                    }
                    console.log('vm.showme=' + vm.showme);
                });
            }
        })();
    </script>
</body>
</html>

This is of course a test app, but the pageslide referenced by the vm.showme will not open when vm.showme is set to true.  Thoughts?

**Comment by dpiccone** [comment]
I can't see any scope involved in this. 
Check this answer http://stackoverflow.com/questions/11605917/this-vs-scope-in-angularjs-controllers
