### ISSUE TITLE
UI router and binding not working?

### ISSUE THREAD

**Issue by benlooi** [dpiccone/ng-pageslide#37]
Hi, tried to navigate to another part of document from slide menu.

However the links are not working. It can work if it is not within the pageslide directive. Seems it is not 

I tried opening with two methods.

       <a  class="btn btn-info pull-right" ng-click="checked=!checked">Open</a>
       <a  class="btn btn-info pull-right" pageslide  ps-side="right" ps-speed="1.0" href="#sidemenu" ps-auto-close>MENU</a>

Binding for href, and ui-sref does not work.

For a href, it does not bind with my $scope.loggeduser.usrID. When mouseover it shows the tooltip with url loggedin/posts/{{loggeduser.userID}} instead of a number like was supposed to.
For UI sref it doesn't work.

    <pageslide ps-open="checked" ps-target="#sidemenu"></pageslide> 
       <div id='sidemenu'>
        <a id="sidemenu-close" class="btn" >Close</a>
        <ul>
           <li> <a href='#/loggedin/posts/{{loggeduser.userID}}'>Home</a></li>
           <li class='dropdown'><a ui-sref='loggedin.create'>Create</a>
            <ul class='submenu-create'>
                <li class='dropdown'><a ui-sref='loggedin.addalbum' >Add new album</a></li>
               <li class='dropdown'>Playlist</li>
          > </ul>
        </li>
        <li class='dropdown'><a ui-sref='loggedin.create'>Discover</a>
            <ul class='submenu-create'>
                <li class='dropdown'>Artistes</li>
                <li class='dropdown'><a ui-sref='loggedin.users'>Users</a></li>
            </ul>
        </li>
    
    
        <li class='dropdown'><a ui-sref='loggedin.create'>Manage</a>
            <ul  class='submenu-create'>
                <li class='dropdown'><a ui-sref='loggedin.report' >Sales report</a></li>
                <li class='dropdown'>Rewards and Payments</li>
                 <li class='dropdown'><a ui-sref='loggedin.profile' >Personal Details</a></li>
            </ul>
        </li>
    
      </ul>

    
</div>  

Any one else has this issue?

**Comment by benlooi** [comment]
Hi all, just an update on getting a slide menu.

Ditched the directive approach because it is screwing up my scope when it is nested.

Here's what I did and it worked.

In CSS:
I have an id called #sidemenu:
    #sidemenu {
    padding:0px;
 
    height:100%;

}
Added 2 classes:

    .hidemenu {
     position: absolute;
     right:0px;
    width:300px;
    background-color:gray;
    opacity:0.9;
     transition: all 0.5s;
}

.showmenu {
     position: absolute;
    right:-300px;
    width:300px;
    display:block;
    background-color:lightgray;
    opacity:0.3;
    transition: all 0.5s;
}

----- in HTML, I used ng-class on element '#sidemenu'. 
    <div id='sidemenu' ng-class="{hidemenu:checked, showmenu:!checked}">
    
</div>

**Comment by EngineeredTruth** [comment]
Benlooi, thanks for that solution. That looks like the easiest possible slidemenu, I understand the concept now.

Do you happen to know how to easily do the 'push' effect?
