### ISSUE TITLE
Add option to specify parent container for the pageslide html

### ISSUE THREAD

**Issue by fbliss** [dpiccone/ng-pageslide#42]
Hi,

We've noticed that the directive appends a new DIV out to the very bottom of the page right above the BODY tag - this is causing our HTML to render incorrectly, forcing a footer to occur above the page slide DIV.  Is there a way to stop this from happening?

**Comment by dpiccone** [comment]
The pageslide should be relative to a fixed viewport (=be a child of <body>) while the rest of the document follows his own structure. Can you be more specific, what do you mean by incorrectly?

**Comment by fbliss** [comment]
Sorry, one of our divs (a angular-google-map directive) was set to height, 0 so the footer is not an issue now.  Now we're just trying to get the slide-out to layer within the bounds of the map directive itself and stay relative to that div while overlaying the map.

**Comment by fbliss** [comment]
Ahh okay, so we want the slider to be absolute, not fixed, and for it to appear within the confined of a parent div so, Let me request that the slider can be appended to the parent element of our choosing (div) and that the position can be switched via option - ps-parentcontainer="<selector>" or something like that.

**Comment by maikdiepenbroek** [comment]
Yes please, this would be much appreciated. I'm working on the enhancement, if it works i'll submit a PR

**Comment by dpiccone** [comment]
@maikdiepenbroek I have corrected the formatting and merged this to the master branch
