### ISSUE TITLE
push option forces content off screen

### ISSUE THREAD

**Issue by smunro16** [dpiccone/ng-pageslide#43]
How do you fix the position of content to avoid it being pushed off screen when using ps-push=true?

E.g.  if you change ps-side="right" on  the push example like below:

            <h3>Push content</h3>
            <div ng-controller="pageslideCtrl">
                <a class="tiny button" href="" ng-click="toggle()">Open Sidebar</a>
                <div pageslide ps-open="checked" ps-side="right" ps-push="true" >
                    <div style="padding:20px" id="demo-right">
                        <h2>Hello Pageslide</h2>
                        <p>Put here whatever you want</p>
                        <a ng-click="toggle()" class="button" >Close</a>
                    </div>
                </div>
            </div>

When you invoke the button all content is forced off to the left of screen. Is there a way to avoid this and have content resize?

**Comment by Prabhaker** [comment]
@smunro16 do you have fix for this problem?

**Comment by Prabhaker** [comment]
ps-squeeze="true" will do it but it does not work well in firefox
