### ISSUE TITLE
psContainer ignored

### ISSUE THREAD

**Issue by artemverbo** [dpiccone/ng-pageslide#52]
Hi! Very nice component, thanks a lot! Just wondering about the psContainer property, by the look in the source code, seems like psContainer is ignored at all and appends to body always. Thank you.

**Comment by dpiccone** [comment]
Hi, thanks for spotting it. It was fixed with the last build

**Comment by asureshhegde** [comment]
Hey guys, very nice library, but trying to make my whole site as a container and I'm trying to open pageslide from right of my container. I have set ps-container="siteWrap" (here siteWrap is the id of the parent div) but it is not working.

So if any of you guys had the same problem or if anyone has solution for this please let me know

Thank you.
