### ISSUE TITLE
title bar (on-top)

### ISSUE THREAD

**Issue by pmMarianP** [dpiccone/ng-pageslide#58]
Is there any possibility to put a title bar on top of the pageslider?
Here is an example from an android app: http://www.axure.com/c/attachments/forum/6-x-newbie-questions/1879d1369172569-creating-android-navigation-drawer-navigation_drawer_holo_dark_light.png

So my goal is to add a title bar but still move the body-content within the pageslider. In the photo-example the shown pageslider just overlaps the body-content.

I tried to play with the ps-container - something like this:

`<a ng-click="toggle()">Open Sidebar</a>`
`<h2>nice title here</h2>`

`<pageslide "some awesome attr" ps-container="maincontent">"nice content"</pageslider>`

`<div id="maincontent>"the main content of the website"</div>`

but it's not gonna work out. Any suggestions?

**Comment by jftsaraiva** [comment]
I think you could use `ps-custom-top`, like this:

```
<div pageslide ps-open="checked" ps-side="left" ps-custom-top="160px">
```
