### ISSUE TITLE
Support for Angular 1.4.3

### ISSUE THREAD

**Issue by tmcgee123** [dpiccone/ng-pageslide#59]
Is there anything pending for support of Angular 1.4.3? There are breaking changes made to ngAnimate. 

Here's a link to the changes: http://angularjs.blogspot.mx/2015/05/angular-140-jaracimrman-existence.html

**Comment by dpiccone** [comment]
There should be no changes since we are not using ngAnimate

**Comment by tmcgee123** [comment]
The directive works fine on Angular 1.4.3, it might be worth it to update the dependency in the bower.json file in order to stay up to date in the progression towards 2.0 (and it keeps pesky developers like me from asking questions like this). 

Cheers!
