### ISSUE TITLE
Why not as a singleton service?

### ISSUE THREAD

**Issue by calebfaruki** [dpiccone/ng-pageslide#62]
Just an informative question. I very much like the idea of this being implemented as a service, not unlike the one described here:

http://weblogs.asp.net/dwahlin/building-an-angularjs-modal-service

Please do let me know what you think of this idea because I do like this library very much so far.

**Comment by dpiccone** [comment]
I think that the directive approach looks cleaner to me, since you don't have to manually define the service interfaces and view bindings but do all in the directive itself
