### ISSUE TITLE
Backdrop

### ISSUE THREAD

**Issue by DHoffm** [dpiccone/ng-pageslide#63]
Hi, any plans on including a backdrop overlay when opening the pageslide. This should also be clickable to close the pageslide?

**Comment by dpiccone** [comment]
Hi, can you give an example ?

**Comment by DHoffm** [comment]
Here is an example:
http://plnkr.co/edit/G7vMSv?p=preview

Just hit one of the buttons (up, down or right).
The background then gets darkened and if you click on it the slide is closed.

**Comment by DHoffm** [comment]
Hi, any updates on that?

**Comment by dpiccone** [comment]
I understand, I think it's interesting providing an option to set a class on the container as well (like body) but the darkening and such is part of the bootstrap framework

**Comment by dpiccone** [comment]
Added ps-body-class if set to true sets a class on the container, in the examples folder you can find the custom css for dimming the background
