### ISSUE TITLE
Top/Left/Bottom/Right Animation instead of Width/Height Animation

### ISSUE THREAD

**Issue by DHoffm** [dpiccone/ng-pageslide#64]
You might need to change the overall animation to top,bottom, left, right because the content of the pageslide always gets squeezed when animating the width or height. This way the content is always pushed instead of scaled up and down. Looks way better in my opinion.

**Comment by dpiccone** [comment]
It requires more work to define all the parameters that are implement now. I started refactoring but didn't have time to finish.
Btw, the content doesn't have to be squeezed, there are examples in which the content appears after the animation, check those for reference

**Comment by DHoffm** [comment]
Appreciate your efforts. I noticed those examples but it looks smoother if the content appears at the same time the slide is opening.
