### ISSUE TITLE
Panel Overflow

### ISSUE THREAD

**Issue by zekth** [dpiccone/ng-pageslide#66]
Default overflow is hidden, which makes some issues with big forms.
Just added theses lines:
line 9:
        return {
            restrict: "EAC",
            transclude: false,
            scope: {
                psOpen: "=?",
                psAutoClose: "=?",
                psSide: "@",
                psSpeed: "@",
                psClass: "@",
                psSize: "@",
                psSqueeze: "@",
                psCloak: "@",
                psPush: "@",
                psContainer: "@",
                psOverflow: "@"
            }

line 44: 
                param.overflow = $scope.psOverflow || 'hidden';

line 75 
                slider.style.overflow = param.overflow;

And in the html i can use this :  ps-overflow="scroll" 

I think it could be interesting to add it. BTW awesome directive.

**Comment by dpiccone** [comment]
Overflow has been removed, now it can be set through css if needed
