### ISSUE TITLE
Setting custom z-index

### ISSUE THREAD

**Issue by kaelle** [dpiccone/ng-pageslide#69]
The .js file suggests using custom CSS to set the z-index.  I tried setting the z-index in several different places through my app to no avail.

Each time an inline style was placed that clobbered any custom CSS I added.

In order to deal with this I added a variable to the scope at line 23:
```
return {
    restrict: "EAC",
    transclude: false,
    scope: {
        psOpen: "=?",
        psAutoClose: "=?",
        psSide: "@",
        psSpeed: "@",
        psClass: "@",
        psSize: "@",
        psSqueeze: "@",
        psCloak: "@",
        psPush: "@",
        psContainer: "@",
        psZindex: "@" // <--- my new scope variable
    },
```

Then at line 38:
```
    param.zindex = $scope.psZindex || 1000; // Override with custom CSS
```

Am I doing it wrong or would this be a useful update?

**Comment by dpiccone** [comment]
Yes, it could be useful

**Comment by dpiccone** [comment]
#100
