### ISSUE TITLE
Can not use ng-pageslide with angular 1.4.7 (in Ruby on Rails)

### ISSUE THREAD

**Issue by ziomio** [dpiccone/ng-pageslide#73]
In my Rails project I use bower packages through Rails Assets.
Rails Assets is the frictionless proxy between Bundler and Bower:
http://rails-assets.org/

But with your package (ng-pageslide) I get dependency conflict because my version of angular is 1.4.7, 
but ng-pageslide (v1.0.5) requires angular = 1.3.15

If we download latest version of ng-pageslide from rails-assets we can see in metadata file - it requires angular '= 1.3.15':
http://rails-assets.org/gems/rails-assets-ng-pageslide-1.0.5.gem

I googled and find a similar issue with another library - problem was because an owner **'force pushed release'**:
https://github.com/rails-assets/rails-assets/issues/198#issuecomment-66326398

I think here is the similar problem. Therefore to fix this issue please change angular dependency to >= 1.3.15 and create new release.

**Comment by tmcgee123** [comment]
Please use the latest version. 1.0.8 has the latest version of angular as a dependency.

**Comment by ziomio** [comment]
The problem is that latest release version is 1.0.5
https://github.com/dpiccone/ng-pageslide/releases
And Rails Assets creates a special Ruby packages only from **releases**
So even though current version is 1.0.8 latest release is still 1.0.5

My solution for this problem was to directly copy source ngPageslide JS file into my project.

**Comment by dpiccone** [comment]
Sorry for the inconvenience. 
I had troubles keeping in sync the bower and npm package manifest files, only because I forgot to do so, nothing was force pushed.

The bower file is in sync with the last package.json file now.
