### ISSUE TITLE
squeeze doesn't unsqueeze, found fix

### ISSUE THREAD

**Issue by k2lh** [dpiccone/ng-pageslide#74]
I like the squeeze option, but when I pulled the repo and tried to reproduce things on my local, I couldn't get the main body to unsqueeze, having squeezed. I'm not sure if this is b/c I'm using bootstrap and it's lacking something foundation does, but I ended up going through the code until I got at least some idea of what's going on. Marking this here in case anyone else runs into similar issue. 

In the src version of the directive (which the demo uses, instead of dist), you need to add this to                                       

    setBodyPosition({left: '0px'});

to line 175, so the psClose function will look like this:

          case 'left':
                setSliderDimension({width: '0px'});
                if (param.squeeze) {
                          setSliderPosition({left: '0px'});
                          setBodyPosition({left: '0px'});
                }

without that, the body's applied style remains 300px to the left, and it never unsqueezes. 

Of course, if I totally missed some switch somewhere that isn't in the dist version but should be, and would fix this w/out intervention, pls do tell. Was a little disappointed for a bit, thinking I'd found such a great little directive but it just wouldn't work in Chrome. But it works now! :)

**Comment by dpiccone** [comment]
The directive will work in bootstrap as well as foundation as it's not framework specific.

There was a refactoring lately, can you try to reproduce the bug rolling back this commit and see if you still have the same problem? 

https://github.com/dpiccone/ng-pageslide/commit/42df918d731944e8eb8c6ff111af314c7e10374c

**Comment by chriiisiscoding** [comment]
That fix worked for me. Thanks!
