### ISSUE TITLE
Feature Request: Multiple nested panels

### ISSUE THREAD

**Issue by brandon-adams** [dpiccone/ng-pageslide#77]
I really like the functionality being provided here,but I'm looking for a bit more. Specifically, I'd like to find a way to nest a slider within a slider, and have the inner one open next to/above/below its parent slider. I'm just fiddling around with this for now, starting with opening left to right, but would you have any idea as to where to start?

**Comment by dpiccone** [comment]
I think it should be possible by nesting the first pageslide into the second, provided that the $compile priority has the right order.

This is not an use case I am supporting however, while it should be possible to have multiple pageslides, having one nested inside another is an edge case in my opinion.
