### ISSUE TITLE
Is there a way of making this PageSlide resizeable? 

### ISSUE THREAD

**Issue by Basicben** [dpiccone/ng-pageslide#79]
This is how I implement the pageslide
< div id="slide" pageslide ps-container="sidebarLeft" ps-side="{{siteComponents.sideBar.side}}" ps-class="{{siteComponents.sideBar.class}}" ,
         ps-open="siteComponents.sideBar.isOpen" ps-speed="{{siteComponents.sideBar.speed}}" ps-push="{{siteComponents.sideBar.isPush}}"
         ps-auto-close="siteComponents.sideBar.isAutoClose" ps-cloak="{{siteComponents.sideBar.cloak}}"
         ps-squeeze="siteComponents.sideBar.isSqueeze"
</div>

......

</div>

I got to have this one resizeable and it does not work with jquery ui resizeable.

**Comment by dpiccone** [comment]
Use 
```ps-size (optional) = desired height/width of panel (defaults to 300px)```
