### ISSUE TITLE
issue with ps-auto-close=yes and feature request

### ISSUE THREAD

**Issue by kelexel** [dpiccone/ng-pageslide#8]
I'm using ng-pageslide with angular 1.2.16
I have several dead-simple anchors on the page like 
```<a href="/path/to/content">clickme</a>```
When a page is loaded, it loads one of my templates containing ```<pageslide ps-open="true" ps-auto-close="true"></pageslide>``` that wraps around my content.
So I'm using ng-pageslide to create a sliding effect for each loaded page.
But, the problem is if I click any link on page, causing the location change, the already opened pageslide isn't closing.. Even better, the new pageslide stacks bellow the previous one (overlaying all pageslide instances..)..
What can cause this ?
Or, is there a way to tell ng-pageslide to "self destroy"..?

Also, ng-pageslide assumes the content inside the pageslide directive has a display:block; which might not always be the case (for me I need display:table), so might be useful to add a ps-container-style setting accepting an object like {display: table})  to the attributes (?) and thus set in in place of ```content.style.display = 'block';```

**Comment by dpiccone** [comment]
This should be solved in the newer version by the integration with the ngRouter events
