### ISSUE TITLE
Feature Request: add 'state' class to required inner body class

### ISSUE THREAD

**Issue by bdkent** [dpiccone/ng-pageslide#80]
The `ps-body-class` attribute appears to either add the CSS state class to the `ps-container` or, if not provided, to the `document.body`.

I would really love the option for it to be applied to the required inner content `<div>` without having to explicitly name the content container.

**Comment by dpiccone** [comment]
If I understood correctly, can't you do this?
```
<div ... ng-controller="yourCtrl">
    ...
    <pageslide ps-open="checked">
        <div className='CUSTOMCLASS'>
            <p>some random content...</p>
        </div>
    </pageslide>
    ...
</div>
```
