### ISSUE TITLE
Feature Request: add a backdrop?

### ISSUE THREAD

**Issue by musso** [dpiccone/ng-pageslide#82]
Could you add the optional backdrop, something like the bootstrap modal...
1. click anywhere outside the slide to close the pageslide
2. skip the unwanted scroll effect or other effect when the pageslide is opened

**Comment by guikubivan** [comment]
You might want to check out https://github.com/dbtek/angular-aside. I would've used that one too, but I wanted the opposite (be able to interact with the page).

**Comment by dpiccone** [comment]
This can be an interaction feature like ps-squeeze and ps-push something like ps-shade=true could prevent the user to click on the underlying body and dim the body.
