### ISSUE TITLE
ps-key-listener should toggle ps-open boolean or accept a callback where boolean can be set

### ISSUE THREAD

**Issue by miketeix** [dpiccone/ng-pageslide#84]
When you hit ```esc``` key, pageslide closes but does not flip the ps-open boolean. 

It would be nice if it did that, but even moreso if it accepted a reference to a handler/callback which could be executed on pressing escape.

Thanks!

**Comment by pedro-mass** [comment]
+1, at the very least it should flip the boolean

**Comment by dpiccone** [comment]
I released a patch for this recently that should fix this issue https://github.com/dpiccone/ng-pageslide/commit/fd2700728d5aa975694d9fe33785decdcd339ec9.

There is also a test covering the psOpen switch when pressing esc https://github.com/dpiccone/ng-pageslide/blob/master/test/directiveSpec.js#L352

However I believe the scope digest cycles need refactoring as they overlap without the $timeout patch.
