### ISSUE TITLE
Webpack support

### ISSUE THREAD

**Issue by wendellm** [dpiccone/ng-pageslide#85]
You have this package up on npm but when requiring it with webpack it throws an error.

I want to do this like with all the angular components from google like angular-resource.
var app = angular.module("app", [require("angular-pageslide-directive")]);
but modules are not supported in your library could you please fix this for those who love using webpack in combination with excellent angular directives like yours?

I have no clue how to do it myself else I would.

Thanks

**Comment by dpiccone** [comment]
Aaccording to this article is just about specifying the dependency
http://angular-tips.com/blog/2015/06/using-angular-1-dot-x-with-es6-and-webpack/
Does this solves your problem?

**Comment by dpiccone** [comment]
Any news about if this problem has been solved?

**Comment by dpiccone** [comment]
Took some time to setup a boilerplate project with a bundler and this directive, I added an UMD module definition that works with Webpack.
