### ISSUE TITLE
Second pageslider pushes content under the first

### ISSUE THREAD

**Issue by wendellm** [dpiccone/ng-pageslide#87]
I have a scenario that calls for a menu to popup from the left and push the content to the right works great. But I don't think that the first pageslide should push the content off canvas (which it does) or it should be at least configurable to not do that but shrink the main container. The second pageslider pushes the content back under the first slider. It does not take into consideration that a slider is already open. Here's a [pen](http://codepen.io/wendellm/pen/RrWydE) of the situation. This is a bug right not a feature? ;)  Just my two cents what you think?

**Comment by psyklopz** [comment]
Using "squeeze" instead of "push" doesn't what you need?  Seems to work for me.
http://codepen.io/anon/pen/Wrjybo
