### ISSUE TITLE
Msbuild is failing due to some mismatch in the version

### ISSUE THREAD

**Issue by gthuruv** [dpiccone/ng-pageslide#89]
Getting the following error when trying to run a msbuild definition.

bower angular-pageslide-directive#^1.0.8         mismatch Version declared in the json (1.0.6) is different than the resolved one (1.0.8)

This is what my bower.json looks like.

{
  "dependencies": {
    "angular": "^1.4.7",
    "angular-animate": "^1.4.7",
    "angular-bootstrap": "^0.14.3",
    "angular-gridster": "^0.13.5",
    "angular-loading-bar": "^0.8.0",
    "angular-moment": "^0.10.3",
    "angular-multi-select": "^4.0.0",
    "angular-pageslide-directive": "^1.0.8",
    "angular-sanitize": "^1.4.7",
    "angular-spinner": "^0.8.0",
    "angular-touch": "^1.4.7",
    "angular-ui-grid": "^3.0.7",
    "angular-ui-router": "^0.2.15",
    "bootstrap": "^3.0.0",
    "bootstrap-touch-carousel": "^0.8.0",
    "breeze-client": "^1.5.4",
    "font-awesome": "^4.4.0",
    "hammer.js": "^2.0.4",
    "jquery": "^2.1.4",
    "jquery-validation": "^1.11.1",
    "jquery-validation-unobtrusive": "^3.2.2",
    "json-formatter": "^0.4.0",
    "jstree": "^3.2.1",
    "modernizr": "2.8.3",
    "moment": "^2.10.6",
    "ng-dialog": "^0.5.5",
    "q": "^2.0.2",
    "requirejs": "^2.1.20",
    "respond": "^1.4.2",
    "spin.js": "^2.3.2",
    "toastr": "^2.1.2"
  },
  "name": "ASP.NET",
  "private": true,
  "resolutions": {
    "angular": "^1.4.7"
  }
}

**Comment by chrizzzzz** [comment]
The version in bower.json seems to be lagging behind.

**Comment by gthuruv** [comment]
Hey @chrizzzzz! thanks for the quick reply. Do you mean version in the ng-pageslide release is lagging? Is there a workaround for this or do I have to downgrade and see if that works?

Thanks!

**Comment by chrizzzzz** [comment]
I don't think you need to worry about the warning, I think Bower gets the version from the git tag, so you get the right version, but it compares it with the bower.json file and see a mismatch.

**Comment by gthuruv** [comment]
Yes. I noticed that ideally it should throw a warning. But in my case the build itself is failing. Looks like msbuild is treating warnings from bower as errors. I might have to find a way to ignore them (fairly new to msbuild!!). Thanks for your help!

**Comment by chrizzzzz** [comment]
Ok I see. Good luck! And no problem.

**Comment by gthuruv** [comment]
Adding "Ignore: []" in the bower.json stopped msbuild from failing!
