### ISSUE TITLE
ps-auto-close not working

### ISSUE THREAD

**Issue by NickToye** [dpiccone/ng-pageslide#92]
Hi,

I'm using the ng-pageslide as a mobile slideout navigation menu, so I have a bunch of menu items that navigate away to other pages.

I have **ps-auto-close** set to **true**, and initially this works, it closes the menu and navigates to that menu page, however the ng-click="toggle()" no longer works unless I refresh the page.

`<div ng-controller="pageslideCtrl">
	<header ng-include="'views/partials/header.html'"></header>
	<ng-include src="'views/partials/nav.html'"></ng-include>
</div>`

Within my header partial:

`<button class="menu-toggle" ng-click="toggle()">
	<span></span>
	<span></span>
	<span></span>
</button>`

Within my nav partial:

`<div pageslide ps-open="checked" class="ng-isolate-scope ng-pageslide" ps-custom-top="0" ps-size="100%" ps-side="left" ps-cloak="false" ps-auto-close="true" style="z-index: 1000; position: fixed; width: 100%; height: 100%; overflow: hidden; transition-duration: 0.5s; transition-property: width, height; top: 0px; bottom: 0px; right: 0px;">
		<nav class="navbar">
			<div class="container">
				<div class="menu-bar">
				<div class="desk-ph++">
					<ul class="menu list-inline unstyled uppercase layout layout--center">
						<li><a href="/#/link">Link</a></li>
					</ul>
				</div>
			</div>
			</div>
		</nav>
	</div>`

Controller:

`app.controller('pageslideCtrl',['$scope',function($scope){
		$scope.checked = false; // This will be binded using the ps-open attribute
		$scope.toggle = function(){
			$scope.checked = !$scope.checked
		}
	}]);`

Is this a bug or have I missed something?

**Comment by pedro-mass** [comment]
I'm having the same issue too. Any updates on a fix?

**Comment by DarthBender** [comment]
Same here.
Please, make sure that escKeyListener calls scope.$apply method

**Comment by dpiccone** [comment]
This should be fixed with https://github.com/dpiccone/ng-pageslide/commit/fd2700728d5aa975694d9fe33785decdcd339ec9

However I don't feel the solution is the best one but avoiding the timeout was causing a $digest already in progress error from tests, which I believe can be replicated in real-life.
