### ISSUE TITLE
Problem using pageslide with ng-repeat and templated container id

### ISSUE THREAD

**Issue by AutoGibbon** [dpiccone/ng-pageslide#93]
As explained in title, we are trying to use ng-pageslide inside an ng-repeat, where the ps-container attribute is defined with angular markup template.

`<pageslide ps-open="false" ps-size="100px" ps-container="dashpanel{{dashitem.dashboardItemId}}">`

**Comment by dpiccone** [comment]
At the time  pageslide is compiled the ng-directive is not yet compiled hence ps-container does not find the container.

http://stackoverflow.com/questions/19254705/index-of-ng-repeat-computed-after-linker-function-of-angular-directive-co

This is not related to this directive but to how directives interact

**Comment by wiggitamoo** [comment]
@AutoGibbon did you find a solution to your problem? I'm having the same problem where i'm trying to reference a dynamic id of a widget

```
<li "ng-repeat="w in widgets">
    <div id="widget-{{w.id}}"></div>
</li>
```

i'm trying to bind the id to ps-container in the same ng-repeat without success
```
<pageslide ps-container="widget-{{w.id}}">
    <div>
        <p>some random content...</p>
    </div>
</pageslide>
```

Any thoughts for how we can use pageslide to do this?
