### ISSUE TITLE
ng-pageslide scrolling to page height

### ISSUE THREAD

**Issue by asureshhegde** [dpiccone/ng-pageslide#96]
Hi, I have used ng-pageslide as the modal poping from right and have used overlay by setting ps-body-class to true, but my problem is as I scroll my modal even the contents behind the overlay scrolls.
So does anyone have a solution for this?

Please let me know if anyone had the same issue or anyone knows the solution 

Thank you.

**Comment by dpiccone** [comment]
By default the pageslide sticks to the body size  which I believe in this case overflows from the viewport.

You should be setting the body height to 100% of the viewport and have a wrapper for the content inside.
You should be doing the same for the pageslide to be able to scroll inside it.

I doesn't sound something related to the directive though.
