### ISSUE TITLE
Remove hardcode overflow

### ISSUE THREAD

**Issue by KingWu** [dpiccone/ng-pageslide#99]
i found this code
`slider.style.overflow = 'hidden';`

this override the custom css

**Comment by Rouche** [comment]
I agree, expose it via ps-overflow?

Meanwhile you can override it with
```
.ng-pageslide {
    background: #eee;
    overflow-y: scroll !important;
}
```

**Comment by pedro-mass** [comment]
preferred using auto for overflow so that it only appears when needed

`.ng-pageslide {
    overflow: auto !important;
}`

**Comment by dpiccone** [comment]
The purpose of having a sliding panel is to separate the content beetween the page and the pageslide, while overriding with !important is possible, I don't think implementing this use case is relevant.

**Comment by pedro-mass** [comment]
The override was so that when the content on the pageslide was longer than the visible space, scroll bars appear so that the user can scroll for the rest of the content.

It's still two separate contents from the page and the pageslide, and each can now have their own scrolling.

**Comment by dpiccone** [comment]
+1 for addressing the scrolling issue, but I'd rather revert to automatic overflow and overrides with css.
This issue has relations to the ps-cloak attribute as well, next version will not have ps-cloak as hiding content before the pageslide is fully open will be the only behaviour.
